name: Publish Crate package

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install toml-cli
        run: cargo install toml-cli
      
      - name: Check Cargo.toml version matches release tag
        run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"

      - name: Publish Crate
        run: cargo publish --locked --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
